export enum VehicleDocumentType {
  REGISTRATION = 'REGISTRATION',
  INSURANCE = 'INSURANCE',
  PROOF_OF_OWNERSHIP = 'PROOF_OF_OWNERSHIP',
  VEHICLE_PERMIT = 'VEHICLE_PERMIT',
  ROADWORTHINESS = 'ROADWORTHINESS',
}
