export enum MailType {
    USER_CONFIRMATION = 'USER_CONFIRMATION',
    RESET_PASSWORD = 'RESET_PASSWORD',
    USER_CREDENTIALS = 'USER_CREDENTIALS',
    IN_APP_EMAIL = 'IN_APP_EMAIL',
    ANNOUNCEMENTS = 'ANNOUNCEMENTS',
    REMINDERS = 'REMINDERS',
    UPDATES = 'UPDATES',
  }
  

  
  