export const countriesSeed = [
  {
    name: 'Afghanistan',
    alpha2code: 'AF',
    alpha3code: 'AFG',
    callingCode: '93',
    continent: 'Asia',
    currencies: ['AFN'],
  },
  {
    name: 'Åland Islands',
    alpha2code: 'AX',
    alpha3code: 'ALA',
    callingCode: '358',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Albania',
    alpha2code: 'AL',
    alpha3code: 'ALB',
    callingCode: '355',
    continent: 'Europe',
    currencies: ['ALL'],
  },
  {
    name: 'Algeria',
    alpha2code: 'DZ',
    alpha3code: 'DZA',
    callingCode: '213',
    continent: 'Africa',
    currencies: ['DZD'],
  },
  {
    name: 'American Samoa',
    alpha2code: 'AS',
    alpha3code: 'ASM',
    callingCode: '1',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Andorra',
    alpha2code: 'AD',
    alpha3code: 'AND',
    callingCode: '376',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Angola',
    alpha2code: 'AO',
    alpha3code: 'AGO',
    callingCode: '244',
    continent: 'Africa',
    currencies: ['AOA'],
  },
  {
    name: 'Anguilla',
    alpha2code: 'AI',
    alpha3code: 'AIA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Antarctica',
    alpha2code: 'AQ',
    alpha3code: 'ATA',
    callingCode: '672',
    continent: 'Polar',
    currencies: ['GBP'],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2code: 'AG',
    alpha3code: 'ATG',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Argentina',
    alpha2code: 'AR',
    alpha3code: 'ARG',
    callingCode: '54',
    continent: 'Americas',
    currencies: ['ARS'],
  },
  {
    name: 'Armenia',
    alpha2code: 'AM',
    alpha3code: 'ARM',
    callingCode: '374',
    continent: 'Asia',
    currencies: ['AMD'],
  },
  {
    name: 'Aruba',
    alpha2code: 'AW',
    alpha3code: 'ABW',
    callingCode: '297',
    continent: 'Americas',
    currencies: ['AWG'],
  },
  {
    name: 'Australia',
    alpha2code: 'AU',
    alpha3code: 'AUS',
    callingCode: '61',
    continent: 'Oceania',
    currencies: ['AUD'],
  },
  {
    name: 'Austria',
    alpha2code: 'AT',
    alpha3code: 'AUT',
    callingCode: '43',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Azerbaijan',
    alpha2code: 'AZ',
    alpha3code: 'AZE',
    callingCode: '994',
    continent: 'Asia',
    currencies: ['AZN'],
  },
  {
    name: 'Bahamas',
    alpha2code: 'BS',
    alpha3code: 'BHS',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['BSD'],
  },
  {
    name: 'Bahrain',
    alpha2code: 'BH',
    alpha3code: 'BHR',
    callingCode: '973',
    continent: 'Asia',
    currencies: ['BHD'],
  },
  {
    name: 'Bangladesh',
    alpha2code: 'BD',
    alpha3code: 'BGD',
    callingCode: '880',
    continent: 'Asia',
    currencies: ['BDT'],
  },
  {
    name: 'Barbados',
    alpha2code: 'BB',
    alpha3code: 'BRB',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['BBD'],
  },
  {
    name: 'Belarus',
    alpha2code: 'BY',
    alpha3code: 'BLR',
    callingCode: '375',
    continent: 'Europe',
    currencies: ['BYN', 'BYR'],
  },
  {
    name: 'Belgium',
    alpha2code: 'BE',
    alpha3code: 'BEL',
    callingCode: '32',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Belize',
    alpha2code: 'BZ',
    alpha3code: 'BLZ',
    callingCode: '501',
    continent: 'Americas',
    currencies: ['BZD'],
  },
  {
    name: 'Benin',
    alpha2code: 'BJ',
    alpha3code: 'BEN',
    callingCode: '229',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Bermuda',
    alpha2code: 'BM',
    alpha3code: 'BMU',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['BMD'],
  },
  {
    name: 'Bhutan',
    alpha2code: 'BT',
    alpha3code: 'BTN',
    callingCode: '975',
    continent: 'Asia',
    currencies: ['BTN', 'INR'],
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2code: 'BO',
    alpha3code: 'BOL',
    callingCode: '591',
    continent: 'Americas',
    currencies: ['BOB'],
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2code: 'BQ',
    alpha3code: 'BES',
    callingCode: '599',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2code: 'BA',
    alpha3code: 'BIH',
    callingCode: '387',
    continent: 'Europe',
    currencies: ['BAM'],
  },
  {
    name: 'Botswana',
    alpha2code: 'BW',
    alpha3code: 'BWA',
    callingCode: '267',
    continent: 'Africa',
    currencies: ['BWP'],
  },
  {
    name: 'Bouvet Island',
    alpha2code: 'BV',
    alpha3code: 'BVT',
    callingCode: '47',
    continent: 'Antarctic Ocean',
    currencies: ['NOK'],
  },
  {
    name: 'Brazil',
    alpha2code: 'BR',
    alpha3code: 'BRA',
    callingCode: '55',
    continent: 'Americas',
    currencies: ['BRL'],
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2code: 'IO',
    alpha3code: 'IOT',
    callingCode: '246',
    continent: 'Africa',
    currencies: ['USD'],
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2code: 'UM',
    alpha3code: 'UMI',
    callingCode: '246',
    continent: 'Americas',
    currencies: ['GBP'],
  },
  {
    name: 'Virgin Islands (British)',
    alpha2code: 'VG',
    alpha3code: 'VGB',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2code: 'VI',
    alpha3code: 'VIR',
    callingCode: '1 340',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Brunei Darussalam',
    alpha2code: 'BN',
    alpha3code: 'BRN',
    callingCode: '673',
    continent: 'Asia',
    currencies: ['BND', 'SGD'],
  },
  {
    name: 'Bulgaria',
    alpha2code: 'BG',
    alpha3code: 'BGR',
    callingCode: '359',
    continent: 'Europe',
    currencies: ['BGN'],
  },
  {
    name: 'Burkina Faso',
    alpha2code: 'BF',
    alpha3code: 'BFA',
    callingCode: '226',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Burundi',
    alpha2code: 'BI',
    alpha3code: 'BDI',
    callingCode: '257',
    continent: 'Africa',
    currencies: ['BIF'],
  },
  {
    name: 'Cambodia',
    alpha2code: 'KH',
    alpha3code: 'KHM',
    callingCode: '855',
    continent: 'Asia',
    currencies: ['KHR', 'USD'],
  },
  {
    name: 'Cameroon',
    alpha2code: 'CM',
    alpha3code: 'CMR',
    callingCode: '237',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Canada',
    alpha2code: 'CA',
    alpha3code: 'CAN',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['CAD'],
  },
  {
    name: 'Cabo Verde',
    alpha2code: 'CV',
    alpha3code: 'CPV',
    callingCode: '238',
    continent: 'Africa',
    currencies: ['CVE'],
  },
  {
    name: 'Cayman Islands',
    alpha2code: 'KY',
    alpha3code: 'CYM',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['KYD'],
  },
  {
    name: 'Central African Republic',
    alpha2code: 'CF',
    alpha3code: 'CAF',
    callingCode: '236',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Chad',
    alpha2code: 'TD',
    alpha3code: 'TCD',
    callingCode: '235',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Chile',
    alpha2code: 'CL',
    alpha3code: 'CHL',
    callingCode: '56',
    continent: 'Americas',
    currencies: ['CLP'],
  },
  {
    name: 'China',
    alpha2code: 'CN',
    alpha3code: 'CHN',
    callingCode: '86',
    continent: 'Asia',
    currencies: ['CNY'],
  },
  {
    name: 'Christmas Island',
    alpha2code: 'CX',
    alpha3code: 'CXR',
    callingCode: '61',
    continent: 'Oceania',
    currencies: ['AUD'],
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2code: 'CC',
    alpha3code: 'CCK',
    callingCode: '61',
    continent: 'Oceania',
    currencies: ['AUD'],
  },
  {
    name: 'Colombia',
    alpha2code: 'CO',
    alpha3code: 'COL',
    callingCode: '57',
    continent: 'Americas',
    currencies: ['COP'],
  },
  {
    name: 'Comoros',
    alpha2code: 'KM',
    alpha3code: 'COM',
    callingCode: '269',
    continent: 'Africa',
    currencies: ['KMF'],
  },
  {
    name: 'Congo',
    alpha2code: 'CG',
    alpha3code: 'COG',
    callingCode: '242',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Congo (Democratic Republic of the)',
    alpha2code: 'CD',
    alpha3code: 'COD',
    callingCode: '243',
    continent: 'Africa',
    currencies: ['CDF'],
  },
  {
    name: 'Cook Islands',
    alpha2code: 'CK',
    alpha3code: 'COK',
    callingCode: '682',
    continent: 'Oceania',
    currencies: ['NZD', 'CKD'],
  },
  {
    name: 'Costa Rica',
    alpha2code: 'CR',
    alpha3code: 'CRI',
    callingCode: '506',
    continent: 'Americas',
    currencies: ['CRC'],
  },
  {
    name: 'Croatia',
    alpha2code: 'HR',
    alpha3code: 'HRV',
    callingCode: '385',
    continent: 'Europe',
    currencies: ['HRK'],
  },
  {
    name: 'Cuba',
    alpha2code: 'CU',
    alpha3code: 'CUB',
    callingCode: '53',
    continent: 'Americas',
    currencies: ['CUC', 'CUP'],
  },
  {
    name: 'Curaçao',
    alpha2code: 'CW',
    alpha3code: 'CUW',
    callingCode: '599',
    continent: 'Americas',
    currencies: ['ANG'],
  },
  {
    name: 'Cyprus',
    alpha2code: 'CY',
    alpha3code: 'CYP',
    callingCode: '357',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Czech Republic',
    alpha2code: 'CZ',
    alpha3code: 'CZE',
    callingCode: '420',
    continent: 'Europe',
    currencies: ['CZK'],
  },
  {
    name: 'Denmark',
    alpha2code: 'DK',
    alpha3code: 'DNK',
    callingCode: '45',
    continent: 'Europe',
    currencies: ['DKK'],
  },
  {
    name: 'Djibouti',
    alpha2code: 'DJ',
    alpha3code: 'DJI',
    callingCode: '253',
    continent: 'Africa',
    currencies: ['DJF'],
  },
  {
    name: 'Dominica',
    alpha2code: 'DM',
    alpha3code: 'DMA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Dominican Republic',
    alpha2code: 'DO',
    alpha3code: 'DOM',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['DOP'],
  },
  {
    name: 'Ecuador',
    alpha2code: 'EC',
    alpha3code: 'ECU',
    callingCode: '593',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Egypt',
    alpha2code: 'EG',
    alpha3code: 'EGY',
    callingCode: '20',
    continent: 'Africa',
    currencies: ['EGP'],
  },
  {
    name: 'El Salvador',
    alpha2code: 'SV',
    alpha3code: 'SLV',
    callingCode: '503',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Equatorial Guinea',
    alpha2code: 'GQ',
    alpha3code: 'GNQ',
    callingCode: '240',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Eritrea',
    alpha2code: 'ER',
    alpha3code: 'ERI',
    callingCode: '291',
    continent: 'Africa',
    currencies: ['ERN'],
  },
  {
    name: 'Estonia',
    alpha2code: 'EE',
    alpha3code: 'EST',
    callingCode: '372',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Ethiopia',
    alpha2code: 'ET',
    alpha3code: 'ETH',
    callingCode: '251',
    continent: 'Africa',
    currencies: ['ETB'],
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2code: 'FK',
    alpha3code: 'FLK',
    callingCode: '500',
    continent: 'Americas',
    currencies: ['FKP'],
  },
  {
    name: 'Faroe Islands',
    alpha2code: 'FO',
    alpha3code: 'FRO',
    callingCode: '298',
    continent: 'Europe',
    currencies: ['DKK', 'FOK'],
  },
  {
    name: 'Fiji',
    alpha2code: 'FJ',
    alpha3code: 'FJI',
    callingCode: '679',
    continent: 'Oceania',
    currencies: ['FJD'],
  },
  {
    name: 'Finland',
    alpha2code: 'FI',
    alpha3code: 'FIN',
    callingCode: '358',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'France',
    alpha2code: 'FR',
    alpha3code: 'FRA',
    callingCode: '33',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'French Guiana',
    alpha2code: 'GF',
    alpha3code: 'GUF',
    callingCode: '594',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'French Polynesia',
    alpha2code: 'PF',
    alpha3code: 'PYF',
    callingCode: '689',
    continent: 'Oceania',
    currencies: ['XPF'],
  },
  {
    name: 'French Southern Territories',
    alpha2code: 'TF',
    alpha3code: 'ATF',
    callingCode: '262',
    continent: 'Africa',
    currencies: ['EUR'],
  },
  {
    name: 'Gabon',
    alpha2code: 'GA',
    alpha3code: 'GAB',
    callingCode: '241',
    continent: 'Africa',
    currencies: ['XAF'],
  },
  {
    name: 'Gambia',
    alpha2code: 'GM',
    alpha3code: 'GMB',
    callingCode: '220',
    continent: 'Africa',
    currencies: ['GMD'],
  },
  {
    name: 'Georgia',
    alpha2code: 'GE',
    alpha3code: 'GEO',
    callingCode: '995',
    continent: 'Asia',
    currencies: ['GEL'],
  },
  {
    name: 'Germany',
    alpha2code: 'DE',
    alpha3code: 'DEU',
    callingCode: '49',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Ghana',
    alpha2code: 'GH',
    alpha3code: 'GHA',
    callingCode: '233',
    continent: 'Africa',
    currencies: ['GHS'],
  },
  {
    name: 'Gibraltar',
    alpha2code: 'GI',
    alpha3code: 'GIB',
    callingCode: '350',
    continent: 'Europe',
    currencies: ['GIP'],
  },
  {
    name: 'Greece',
    alpha2code: 'GR',
    alpha3code: 'GRC',
    callingCode: '30',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Greenland',
    alpha2code: 'GL',
    alpha3code: 'GRL',
    callingCode: '299',
    continent: 'Americas',
    currencies: ['DKK'],
  },
  {
    name: 'Grenada',
    alpha2code: 'GD',
    alpha3code: 'GRD',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Guadeloupe',
    alpha2code: 'GP',
    alpha3code: 'GLP',
    callingCode: '590',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'Guam',
    alpha2code: 'GU',
    alpha3code: 'GUM',
    callingCode: '1',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Guatemala',
    alpha2code: 'GT',
    alpha3code: 'GTM',
    callingCode: '502',
    continent: 'Americas',
    currencies: ['GTQ'],
  },
  {
    name: 'Guernsey',
    alpha2code: 'GG',
    alpha3code: 'GGY',
    callingCode: '44',
    continent: 'Europe',
    currencies: ['GBP', 'GGP'],
  },
  {
    name: 'Guinea',
    alpha2code: 'GN',
    alpha3code: 'GIN',
    callingCode: '224',
    continent: 'Africa',
    currencies: ['GNF'],
  },
  {
    name: 'Guinea-Bissau',
    alpha2code: 'GW',
    alpha3code: 'GNB',
    callingCode: '245',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Guyana',
    alpha2code: 'GY',
    alpha3code: 'GUY',
    callingCode: '592',
    continent: 'Americas',
    currencies: ['GYD'],
  },
  {
    name: 'Haiti',
    alpha2code: 'HT',
    alpha3code: 'HTI',
    callingCode: '509',
    continent: 'Americas',
    currencies: ['HTG'],
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2code: 'HM',
    alpha3code: 'HMD',
    callingCode: '672',
    continent: 'Antarctic',
    currencies: ['AUD'],
  },
  {
    name: 'Vatican City',
    alpha2code: 'VA',
    alpha3code: 'VAT',
    callingCode: '379',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Honduras',
    alpha2code: 'HN',
    alpha3code: 'HND',
    callingCode: '504',
    continent: 'Americas',
    currencies: ['HNL'],
  },
  {
    name: 'Hungary',
    alpha2code: 'HU',
    alpha3code: 'HUN',
    callingCode: '36',
    continent: 'Europe',
    currencies: ['HUF'],
  },
  {
    name: 'Hong Kong',
    alpha2code: 'HK',
    alpha3code: 'HKG',
    callingCode: '852',
    continent: 'Asia',
    currencies: ['HKD'],
  },
  {
    name: 'Iceland',
    alpha2code: 'IS',
    alpha3code: 'ISL',
    callingCode: '354',
    continent: 'Europe',
    currencies: ['ISK'],
  },
  {
    name: 'India',
    alpha2code: 'IN',
    alpha3code: 'IND',
    callingCode: '91',
    continent: 'Asia',
    currencies: ['INR'],
  },
  {
    name: 'Indonesia',
    alpha2code: 'ID',
    alpha3code: 'IDN',
    callingCode: '62',
    continent: 'Asia',
    currencies: ['IDR'],
  },
  {
    name: 'Ivory Coast',
    alpha2code: 'CI',
    alpha3code: 'CIV',
    callingCode: '225',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2code: 'IR',
    alpha3code: 'IRN',
    callingCode: '98',
    continent: 'Asia',
    currencies: ['IRR'],
  },
  {
    name: 'Iraq',
    alpha2code: 'IQ',
    alpha3code: 'IRQ',
    callingCode: '964',
    continent: 'Asia',
    currencies: ['IQD'],
  },
  {
    name: 'Ireland',
    alpha2code: 'IE',
    alpha3code: 'IRL',
    callingCode: '353',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Isle of Man',
    alpha2code: 'IM',
    alpha3code: 'IMN',
    callingCode: '44',
    continent: 'Europe',
    currencies: ['GBP', 'IMP[G]'],
  },
  {
    name: 'Israel',
    alpha2code: 'IL',
    alpha3code: 'ISR',
    callingCode: '972',
    continent: 'Asia',
    currencies: ['ILS'],
  },
  {
    name: 'Italy',
    alpha2code: 'IT',
    alpha3code: 'ITA',
    callingCode: '39',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Jamaica',
    alpha2code: 'JM',
    alpha3code: 'JAM',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['JMD'],
  },
  {
    name: 'Japan',
    alpha2code: 'JP',
    alpha3code: 'JPN',
    callingCode: '81',
    continent: 'Asia',
    currencies: ['JPY'],
  },
  {
    name: 'Jersey',
    alpha2code: 'JE',
    alpha3code: 'JEY',
    callingCode: '44',
    continent: 'Europe',
    currencies: ['GBP', 'JEP[G]'],
  },
  {
    name: 'Jordan',
    alpha2code: 'JO',
    alpha3code: 'JOR',
    callingCode: '962',
    continent: 'Asia',
    currencies: ['JOD'],
  },
  {
    name: 'Kazakhstan',
    alpha2code: 'KZ',
    alpha3code: 'KAZ',
    callingCode: '76',
    continent: 'Asia',
    currencies: ['KZT'],
  },
  {
    name: 'Kenya',
    alpha2code: 'KE',
    alpha3code: 'KEN',
    callingCode: '254',
    continent: 'Africa',
    currencies: ['KES'],
  },
  {
    name: 'Kiribati',
    alpha2code: 'KI',
    alpha3code: 'KIR',
    callingCode: '686',
    continent: 'Oceania',
    currencies: ['AUD', 'KID'],
  },
  {
    name: 'Kuwait',
    alpha2code: 'KW',
    alpha3code: 'KWT',
    callingCode: '965',
    continent: 'Asia',
    currencies: ['KWD'],
  },
  {
    name: 'Kyrgyzstan',
    alpha2code: 'KG',
    alpha3code: 'KGZ',
    callingCode: '996',
    continent: 'Asia',
    currencies: ['KGS'],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2code: 'LA',
    alpha3code: 'LAO',
    callingCode: '856',
    continent: 'Asia',
    currencies: ['LAK'],
  },
  {
    name: 'Latvia',
    alpha2code: 'LV',
    alpha3code: 'LVA',
    callingCode: '371',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Lebanon',
    alpha2code: 'LB',
    alpha3code: 'LBN',
    callingCode: '961',
    continent: 'Asia',
    currencies: ['LBP'],
  },
  {
    name: 'Lesotho',
    alpha2code: 'LS',
    alpha3code: 'LSO',
    callingCode: '266',
    continent: 'Africa',
    currencies: ['LSL', 'ZAR'],
  },
  {
    name: 'Liberia',
    alpha2code: 'LR',
    alpha3code: 'LBR',
    callingCode: '231',
    continent: 'Africa',
    currencies: ['LRD'],
  },
  {
    name: 'Libya',
    alpha2code: 'LY',
    alpha3code: 'LBY',
    callingCode: '218',
    continent: 'Africa',
    currencies: ['LYD'],
  },
  {
    name: 'Liechtenstein',
    alpha2code: 'LI',
    alpha3code: 'LIE',
    callingCode: '423',
    continent: 'Europe',
    currencies: ['CHF'],
  },
  {
    name: 'Lithuania',
    alpha2code: 'LT',
    alpha3code: 'LTU',
    callingCode: '370',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Luxembourg',
    alpha2code: 'LU',
    alpha3code: 'LUX',
    callingCode: '352',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Macao',
    alpha2code: 'MO',
    alpha3code: 'MAC',
    callingCode: '853',
    continent: 'Asia',
    currencies: ['MOP'],
  },
  {
    name: 'North Macedonia',
    alpha2code: 'MK',
    alpha3code: 'MKD',
    callingCode: '389',
    continent: 'Europe',
    currencies: ['MKD'],
  },
  {
    name: 'Madagascar',
    alpha2code: 'MG',
    alpha3code: 'MDG',
    callingCode: '261',
    continent: 'Africa',
    currencies: ['MGA'],
  },
  {
    name: 'Malawi',
    alpha2code: 'MW',
    alpha3code: 'MWI',
    callingCode: '265',
    continent: 'Africa',
    currencies: ['MWK'],
  },
  {
    name: 'Malaysia',
    alpha2code: 'MY',
    alpha3code: 'MYS',
    callingCode: '60',
    continent: 'Asia',
    currencies: ['MYR'],
  },
  {
    name: 'Maldives',
    alpha2code: 'MV',
    alpha3code: 'MDV',
    callingCode: '960',
    continent: 'Asia',
    currencies: ['MVR'],
  },
  {
    name: 'Mali',
    alpha2code: 'ML',
    alpha3code: 'MLI',
    callingCode: '223',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Malta',
    alpha2code: 'MT',
    alpha3code: 'MLT',
    callingCode: '356',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Marshall Islands',
    alpha2code: 'MH',
    alpha3code: 'MHL',
    callingCode: '692',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Martinique',
    alpha2code: 'MQ',
    alpha3code: 'MTQ',
    callingCode: '596',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'Mauritania',
    alpha2code: 'MR',
    alpha3code: 'MRT',
    callingCode: '222',
    continent: 'Africa',
    currencies: ['MRO'],
  },
  {
    name: 'Mauritius',
    alpha2code: 'MU',
    alpha3code: 'MUS',
    callingCode: '230',
    continent: 'Africa',
    currencies: ['MUR'],
  },
  {
    name: 'Mayotte',
    alpha2code: 'YT',
    alpha3code: 'MYT',
    callingCode: '262',
    continent: 'Africa',
    currencies: ['EUR'],
  },
  {
    name: 'Mexico',
    alpha2code: 'MX',
    alpha3code: 'MEX',
    callingCode: '52',
    continent: 'Americas',
    currencies: ['MXN'],
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2code: 'FM',
    alpha3code: 'FSM',
    callingCode: '691',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Moldova (Republic of)',
    alpha2code: 'MD',
    alpha3code: 'MDA',
    callingCode: '373',
    continent: 'Europe',
    currencies: ['MDL'],
  },
  {
    name: 'Monaco',
    alpha2code: 'MC',
    alpha3code: 'MCO',
    callingCode: '377',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Mongolia',
    alpha2code: 'MN',
    alpha3code: 'MNG',
    callingCode: '976',
    continent: 'Asia',
    currencies: ['MNT'],
  },
  {
    name: 'Montenegro',
    alpha2code: 'ME',
    alpha3code: 'MNE',
    callingCode: '382',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Montserrat',
    alpha2code: 'MS',
    alpha3code: 'MSR',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Morocco',
    alpha2code: 'MA',
    alpha3code: 'MAR',
    callingCode: '212',
    continent: 'Africa',
    currencies: ['MAD'],
  },
  {
    name: 'Mozambique',
    alpha2code: 'MZ',
    alpha3code: 'MOZ',
    callingCode: '258',
    continent: 'Africa',
    currencies: ['MZN'],
  },
  {
    name: 'Myanmar',
    alpha2code: 'MM',
    alpha3code: 'MMR',
    callingCode: '95',
    continent: 'Asia',
    currencies: ['MMK'],
  },
  {
    name: 'Namibia',
    alpha2code: 'NA',
    alpha3code: 'NAM',
    callingCode: '264',
    continent: 'Africa',
    currencies: ['NAD', 'ZAR'],
  },
  {
    name: 'Nauru',
    alpha2code: 'NR',
    alpha3code: 'NRU',
    callingCode: '674',
    continent: 'Oceania',
    currencies: ['AUD'],
  },
  {
    name: 'Nepal',
    alpha2code: 'NP',
    alpha3code: 'NPL',
    callingCode: '977',
    continent: 'Asia',
    currencies: ['NPR'],
  },
  {
    name: 'Netherlands',
    alpha2code: 'NL',
    alpha3code: 'NLD',
    callingCode: '31',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'New Caledonia',
    alpha2code: 'NC',
    alpha3code: 'NCL',
    callingCode: '687',
    continent: 'Oceania',
    currencies: ['XPF'],
  },
  {
    name: 'New Zealand',
    alpha2code: 'NZ',
    alpha3code: 'NZL',
    callingCode: '64',
    continent: 'Oceania',
    currencies: ['NZD'],
  },
  {
    name: 'Nicaragua',
    alpha2code: 'NI',
    alpha3code: 'NIC',
    callingCode: '505',
    continent: 'Americas',
    currencies: ['NIO'],
  },
  {
    name: 'Niger',
    alpha2code: 'NE',
    alpha3code: 'NER',
    callingCode: '227',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Nigeria',
    alpha2code: 'NG',
    alpha3code: 'NGA',
    callingCode: '234',
    continent: 'Africa',
    currencies: ['NGN'],
  },
  {
    name: 'Niue',
    alpha2code: 'NU',
    alpha3code: 'NIU',
    callingCode: '683',
    continent: 'Oceania',
    currencies: ['NZD', 'NZD'],
  },
  {
    name: 'Norfolk Island',
    alpha2code: 'NF',
    alpha3code: 'NFK',
    callingCode: '672',
    continent: 'Oceania',
    currencies: ['AUD'],
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2code: 'KP',
    alpha3code: 'PRK',
    callingCode: '850',
    continent: 'Asia',
    currencies: ['KPW'],
  },
  {
    name: 'Northern Mariana Islands',
    alpha2code: 'MP',
    alpha3code: 'MNP',
    callingCode: '1',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Norway',
    alpha2code: 'NO',
    alpha3code: 'NOR',
    callingCode: '47',
    continent: 'Europe',
    currencies: ['NOK'],
  },
  {
    name: 'Oman',
    alpha2code: 'OM',
    alpha3code: 'OMN',
    callingCode: '968',
    continent: 'Asia',
    currencies: ['OMR'],
  },
  {
    name: 'Pakistan',
    alpha2code: 'PK',
    alpha3code: 'PAK',
    callingCode: '92',
    continent: 'Asia',
    currencies: ['PKR'],
  },
  {
    name: 'Palau',
    alpha2code: 'PW',
    alpha3code: 'PLW',
    callingCode: '680',
    continent: 'Oceania',
    currencies: ['USD'],
  },
  {
    name: 'Palestine, State of',
    alpha2code: 'PS',
    alpha3code: 'PSE',
    callingCode: '970',
    continent: 'Asia',
    currencies: ['EGP', 'ILS', 'JOD'],
  },
  {
    name: 'Panama',
    alpha2code: 'PA',
    alpha3code: 'PAN',
    callingCode: '507',
    continent: 'Americas',
    currencies: ['PAB', 'USD'],
  },
  {
    name: 'Papua New Guinea',
    alpha2code: 'PG',
    alpha3code: 'PNG',
    callingCode: '675',
    continent: 'Oceania',
    currencies: ['PGK'],
  },
  {
    name: 'Paraguay',
    alpha2code: 'PY',
    alpha3code: 'PRY',
    callingCode: '595',
    continent: 'Americas',
    currencies: ['PYG'],
  },
  {
    name: 'Peru',
    alpha2code: 'PE',
    alpha3code: 'PER',
    callingCode: '51',
    continent: 'Americas',
    currencies: ['PEN'],
  },
  {
    name: 'Philippines',
    alpha2code: 'PH',
    alpha3code: 'PHL',
    callingCode: '63',
    continent: 'Asia',
    currencies: ['PHP'],
  },
  {
    name: 'Pitcairn',
    alpha2code: 'PN',
    alpha3code: 'PCN',
    callingCode: '64',
    continent: 'Oceania',
    currencies: ['NZD', 'PND'],
  },
  {
    name: 'Poland',
    alpha2code: 'PL',
    alpha3code: 'POL',
    callingCode: '48',
    continent: 'Europe',
    currencies: ['PLN'],
  },
  {
    name: 'Portugal',
    alpha2code: 'PT',
    alpha3code: 'PRT',
    callingCode: '351',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Puerto Rico',
    alpha2code: 'PR',
    alpha3code: 'PRI',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Qatar',
    alpha2code: 'QA',
    alpha3code: 'QAT',
    callingCode: '974',
    continent: 'Asia',
    currencies: ['QAR'],
  },
  {
    name: 'Republic of Kosovo',
    alpha2code: 'XK',
    alpha3code: 'UNK',
    callingCode: '383',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Réunion',
    alpha2code: 'RE',
    alpha3code: 'REU',
    callingCode: '262',
    continent: 'Africa',
    currencies: ['EUR'],
  },
  {
    name: 'Romania',
    alpha2code: 'RO',
    alpha3code: 'ROU',
    callingCode: '40',
    continent: 'Europe',
    currencies: ['RON'],
  },
  {
    name: 'Russian Federation',
    alpha2code: 'RU',
    alpha3code: 'RUS',
    callingCode: '7',
    continent: 'Europe',
    currencies: ['RUB'],
  },
  {
    name: 'Rwanda',
    alpha2code: 'RW',
    alpha3code: 'RWA',
    callingCode: '250',
    continent: 'Africa',
    currencies: ['RWF'],
  },
  {
    name: 'Saint Barthélemy',
    alpha2code: 'BL',
    alpha3code: 'BLM',
    callingCode: '590',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2code: 'SH',
    alpha3code: 'SHN',
    callingCode: '290',
    continent: 'Africa',
    currencies: ['SHP'],
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2code: 'KN',
    alpha3code: 'KNA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Saint Lucia',
    alpha2code: 'LC',
    alpha3code: 'LCA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Saint Martin (French part)',
    alpha2code: 'MF',
    alpha3code: 'MAF',
    callingCode: '590',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2code: 'PM',
    alpha3code: 'SPM',
    callingCode: '508',
    continent: 'Americas',
    currencies: ['EUR'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2code: 'VC',
    alpha3code: 'VCT',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['XCD'],
  },
  {
    name: 'Samoa',
    alpha2code: 'WS',
    alpha3code: 'WSM',
    callingCode: '685',
    continent: 'Oceania',
    currencies: ['WST'],
  },
  {
    name: 'San Marino',
    alpha2code: 'SM',
    alpha3code: 'SMR',
    callingCode: '378',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Sao Tome and Principe',
    alpha2code: 'ST',
    alpha3code: 'STP',
    callingCode: '239',
    continent: 'Africa',
    currencies: ['STD'],
  },
  {
    name: 'Saudi Arabia',
    alpha2code: 'SA',
    alpha3code: 'SAU',
    callingCode: '966',
    continent: 'Asia',
    currencies: ['SAR'],
  },
  {
    name: 'Senegal',
    alpha2code: 'SN',
    alpha3code: 'SEN',
    callingCode: '221',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Serbia',
    alpha2code: 'RS',
    alpha3code: 'SRB',
    callingCode: '381',
    continent: 'Europe',
    currencies: ['RSD'],
  },
  {
    name: 'Seychelles',
    alpha2code: 'SC',
    alpha3code: 'SYC',
    callingCode: '248',
    continent: 'Africa',
    currencies: ['SCR'],
  },
  {
    name: 'Sierra Leone',
    alpha2code: 'SL',
    alpha3code: 'SLE',
    callingCode: '232',
    continent: 'Africa',
    currencies: ['SLL'],
  },
  {
    name: 'Singapore',
    alpha2code: 'SG',
    alpha3code: 'SGP',
    callingCode: '65',
    continent: 'Asia',
    currencies: ['SGD'],
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2code: 'SX',
    alpha3code: 'SXM',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['ANG'],
  },
  {
    name: 'Slovakia',
    alpha2code: 'SK',
    alpha3code: 'SVK',
    callingCode: '421',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Slovenia',
    alpha2code: 'SI',
    alpha3code: 'SVN',
    callingCode: '386',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Solomon Islands',
    alpha2code: 'SB',
    alpha3code: 'SLB',
    callingCode: '677',
    continent: 'Oceania',
    currencies: ['SBD'],
  },
  {
    name: 'Somalia',
    alpha2code: 'SO',
    alpha3code: 'SOM',
    callingCode: '252',
    continent: 'Africa',
    currencies: ['SOS'],
  },
  {
    name: 'South Africa',
    alpha2code: 'ZA',
    alpha3code: 'ZAF',
    callingCode: '27',
    continent: 'Africa',
    currencies: ['ZAR'],
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2code: 'GS',
    alpha3code: 'SGS',
    callingCode: '500',
    continent: 'Americas',
    currencies: ['FKP'],
  },
  {
    name: 'Korea (Republic of)',
    alpha2code: 'KR',
    alpha3code: 'KOR',
    callingCode: '82',
    continent: 'Asia',
    currencies: ['KRW'],
  },
  {
    name: 'Spain',
    alpha2code: 'ES',
    alpha3code: 'ESP',
    callingCode: '34',
    continent: 'Europe',
    currencies: ['EUR'],
  },
  {
    name: 'Sri Lanka',
    alpha2code: 'LK',
    alpha3code: 'LKA',
    callingCode: '94',
    continent: 'Asia',
    currencies: ['LKR'],
  },
  {
    name: 'Sudan',
    alpha2code: 'SD',
    alpha3code: 'SDN',
    callingCode: '249',
    continent: 'Africa',
    currencies: ['SDG'],
  },
  {
    name: 'South Sudan',
    alpha2code: 'SS',
    alpha3code: 'SSD',
    callingCode: '211',
    continent: 'Africa',
    currencies: ['SSP'],
  },
  {
    name: 'Suriname',
    alpha2code: 'SR',
    alpha3code: 'SUR',
    callingCode: '597',
    continent: 'Americas',
    currencies: ['SRD'],
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2code: 'SJ',
    alpha3code: 'SJM',
    callingCode: '47',
    continent: 'Europe',
    currencies: ['NOK'],
  },
  {
    name: 'Swaziland',
    alpha2code: 'SZ',
    alpha3code: 'SWZ',
    callingCode: '268',
    continent: 'Africa',
    currencies: ['SZL'],
  },
  {
    name: 'Sweden',
    alpha2code: 'SE',
    alpha3code: 'SWE',
    callingCode: '46',
    continent: 'Europe',
    currencies: ['SEK'],
  },
  {
    name: 'Switzerland',
    alpha2code: 'CH',
    alpha3code: 'CHE',
    callingCode: '41',
    continent: 'Europe',
    currencies: ['CHF'],
  },
  {
    name: 'Syrian Arab Republic',
    alpha2code: 'SY',
    alpha3code: 'SYR',
    callingCode: '963',
    continent: 'Asia',
    currencies: ['SYP'],
  },
  {
    name: 'Taiwan',
    alpha2code: 'TW',
    alpha3code: 'TWN',
    callingCode: '886',
    continent: 'Asia',
    currencies: ['TWD'],
  },
  {
    name: 'Tajikistan',
    alpha2code: 'TJ',
    alpha3code: 'TJK',
    callingCode: '992',
    continent: 'Asia',
    currencies: ['TJS'],
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2code: 'TZ',
    alpha3code: 'TZA',
    callingCode: '255',
    continent: 'Africa',
    currencies: ['TZS'],
  },
  {
    name: 'Thailand',
    alpha2code: 'TH',
    alpha3code: 'THA',
    callingCode: '66',
    continent: 'Asia',
    currencies: ['THB'],
  },
  {
    name: 'Timor-Leste',
    alpha2code: 'TL',
    alpha3code: 'TLS',
    callingCode: '670',
    continent: 'Asia',
    currencies: ['USD'],
  },
  {
    name: 'Togo',
    alpha2code: 'TG',
    alpha3code: 'TGO',
    callingCode: '228',
    continent: 'Africa',
    currencies: ['XOF'],
  },
  {
    name: 'Tokelau',
    alpha2code: 'TK',
    alpha3code: 'TKL',
    callingCode: '690',
    continent: 'Oceania',
    currencies: ['NZD'],
  },
  {
    name: 'Tonga',
    alpha2code: 'TO',
    alpha3code: 'TON',
    callingCode: '676',
    continent: 'Oceania',
    currencies: ['TOP'],
  },
  {
    name: 'Trinidad and Tobago',
    alpha2code: 'TT',
    alpha3code: 'TTO',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['TTD'],
  },
  {
    name: 'Tunisia',
    alpha2code: 'TN',
    alpha3code: 'TUN',
    callingCode: '216',
    continent: 'Africa',
    currencies: ['TND'],
  },
  {
    name: 'Turkey',
    alpha2code: 'TR',
    alpha3code: 'TUR',
    callingCode: '90',
    continent: 'Asia',
    currencies: ['TRY'],
  },
  {
    name: 'Turkmenistan',
    alpha2code: 'TM',
    alpha3code: 'TKM',
    callingCode: '993',
    continent: 'Asia',
    currencies: ['TMT'],
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2code: 'TC',
    alpha3code: 'TCA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Tuvalu',
    alpha2code: 'TV',
    alpha3code: 'TUV',
    callingCode: '688',
    continent: 'Oceania',
    currencies: ['AUD', 'TVD[G]'],
  },
  {
    name: 'Uganda',
    alpha2code: 'UG',
    alpha3code: 'UGA',
    callingCode: '256',
    continent: 'Africa',
    currencies: ['UGX'],
  },
  {
    name: 'Ukraine',
    alpha2code: 'UA',
    alpha3code: 'UKR',
    callingCode: '380',
    continent: 'Europe',
    currencies: ['UAH'],
  },
  {
    name: 'United Arab Emirates',
    alpha2code: 'AE',
    alpha3code: 'ARE',
    callingCode: '971',
    continent: 'Asia',
    currencies: ['AED'],
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha2code: 'GB',
    alpha3code: 'GBR',
    callingCode: '44',
    continent: 'Europe',
    currencies: ['GBP'],
  },
  {
    name: 'United States of America',
    alpha2code: 'US',
    alpha3code: 'USA',
    callingCode: '1',
    continent: 'Americas',
    currencies: ['USD'],
  },
  {
    name: 'Uruguay',
    alpha2code: 'UY',
    alpha3code: 'URY',
    callingCode: '598',
    continent: 'Americas',
    currencies: ['UYU'],
  },
  {
    name: 'Uzbekistan',
    alpha2code: 'UZ',
    alpha3code: 'UZB',
    callingCode: '998',
    continent: 'Asia',
    currencies: ['UZS'],
  },
  {
    name: 'Vanuatu',
    alpha2code: 'VU',
    alpha3code: 'VUT',
    callingCode: '678',
    continent: 'Oceania',
    currencies: ['VUV'],
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2code: 'VE',
    alpha3code: 'VEN',
    callingCode: '58',
    continent: 'Americas',
    currencies: ['VEF'],
  },
  {
    name: 'Vietnam',
    alpha2code: 'VN',
    alpha3code: 'VNM',
    callingCode: '84',
    continent: 'Asia',
    currencies: ['VND'],
  },
  {
    name: 'Wallis and Futuna',
    alpha2code: 'WF',
    alpha3code: 'WLF',
    callingCode: '681',
    continent: 'Oceania',
    currencies: ['XPF'],
  },
  {
    name: 'Western Sahara',
    alpha2code: 'EH',
    alpha3code: 'ESH',
    callingCode: '212',
    continent: 'Africa',
    currencies: ['MAD', 'DZD'],
  },
  {
    name: 'Yemen',
    alpha2code: 'YE',
    alpha3code: 'YEM',
    callingCode: '967',
    continent: 'Asia',
    currencies: ['YER'],
  },
  {
    name: 'Zambia',
    alpha2code: 'ZM',
    alpha3code: 'ZMB',
    callingCode: '260',
    continent: 'Africa',
    currencies: ['ZMW'],
  },
  {
    name: 'Zimbabwe',
    alpha2code: 'ZW',
    alpha3code: 'ZWE',
    callingCode: '263',
    continent: 'Africa',
    currencies: ['ZMW'],
  },
];
